future: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
github: academicpages
url: https://deto.github.io/group-meeting 
name: Deto's Group
description: A test site to learn about Jekyll
twitter: yourtwitterhandle
calendar: https://yourcalendarurl
mailinglist: https://yourmailinglisturl
gravatar_url: 
disqus_username:
